export const PROVINCES = [
  'Aceh',
  'Sumatera Utara',
  'Sumatera Barat',
  'Riau',
  'Kepulauan Riau',
  'Jambi',
  'Sumatera Selatan',
  'Bangka Belitung',
  'Bengkulu',
  'Lampung',
  'DKI Jakarta',
  'Jawa Barat',
  'Banten',
  'Jawa Tengah',
  'DI Yogyakarta',
  'Jawa Timur',
  'Bali',
  'Nusa Tenggara Barat',
  'Nusa Tenggara Timur',
  'Kalimantan Barat',
  'Kalimantan Tengah',
  'Kalimantan Selatan',
  'Kalimantan Timur',
  'Kalimantan Utara',
  'Sulawesi Utara',
  'Gorontalo',
  'Sulawesi Tengah',
  'Sulawesi Barat',
  'Sulawesi Selatan',
  'Sulawesi Tenggara',
  'Maluku',
  'Maluku Utara',
  'Papua',
  'Papua Barat',
  'Papua Tengah',
  'Papua Pegunungan',
  'Papua Selatan',
];

export const CITIES: Record<string, string[]> = {
  'Aceh': ['Banda Aceh', 'Lhokseumawe', 'Langsa', 'Sabang', 'Meulaboh'],
  'Sumatera Utara': ['Medan', 'Binjai', 'Pematangsiantar', 'Tebing Tinggi', 'Padang Sidempuan'],
  'Sumatera Barat': ['Padang', 'Bukittinggi', 'Payakumbuh', 'Solok', 'Sawahlunto'],
  'Riau': ['Pekanbaru', 'Dumai', 'Bengkalis', 'Siak', 'Kampar'],
  'Kepulauan Riau': ['Batam', 'Tanjung Pinang', 'Bintan', 'Karimun'],
  'Jambi': ['Jambi', 'Sungai Penuh', 'Muaro Jambi', 'Bungo'],
  'Sumatera Selatan': ['Palembang', 'Prabumulih', 'Lubuklinggau', 'Pagar Alam'],
  'Bangka Belitung': ['Pangkal Pinang', 'Sungailiat', 'Manggar', 'Tanjung Pandan'],
  'Bengkulu': ['Bengkulu', 'Curup', 'Manna', 'Arga Makmur'],
  'Lampung': ['Bandar Lampung', 'Metro', 'Pringsewu', 'Kotabumi'],
  'DKI Jakarta': ['Jakarta Pusat', 'Jakarta Utara', 'Jakarta Barat', 'Jakarta Selatan', 'Jakarta Timur'],
  'Jawa Barat': ['Bandung', 'Bogor', 'Depok', 'Bekasi', 'Cirebon', 'Sukabumi', 'Tasikmalaya'],
  'Banten': ['Serang', 'Tangerang', 'Tangerang Selatan', 'Cilegon', 'Pandeglang'],
  'Jawa Tengah': ['Semarang', 'Solo', 'Salatiga', 'Magelang', 'Pekalongan', 'Tegal', 'Kudus'],
  'DI Yogyakarta': ['Yogyakarta', 'Sleman', 'Bantul', 'Gunungkidul', 'Kulon Progo'],
  'Jawa Timur': ['Surabaya', 'Malang', 'Kediri', 'Madiun', 'Mojokerto', 'Blitar', 'Pasuruan'],
  'Bali': ['Denpasar', 'Badung', 'Gianyar', 'Tabanan', 'Buleleng', 'Karangasem'],
  'Nusa Tenggara Barat': ['Mataram', 'Lombok Barat', 'Lombok Timur', 'Sumbawa', 'Bima'],
  'Nusa Tenggara Timur': ['Kupang', 'Ende', 'Maumere', 'Ruteng', 'Labuan Bajo'],
  'Kalimantan Barat': ['Pontianak', 'Singkawang', 'Sambas', 'Ketapang'],
  'Kalimantan Tengah': ['Palangkaraya', 'Sampit', 'Pangkalan Bun', 'Muara Teweh'],
  'Kalimantan Selatan': ['Banjarmasin', 'Banjarbaru', 'Martapura', 'Kandangan'],
  'Kalimantan Timur': ['Samarinda', 'Balikpapan', 'Bontang', 'Tenggarong'],
  'Kalimantan Utara': ['Tarakan', 'Tanjung Selor', 'Nunukan', 'Malinau'],
  'Sulawesi Utara': ['Manado', 'Bitung', 'Tomohon', 'Kotamobagu'],
  'Gorontalo': ['Gorontalo', 'Limboto', 'Tilamuta'],
  'Sulawesi Tengah': ['Palu', 'Poso', 'Luwuk', 'Toli-Toli'],
  'Sulawesi Barat': ['Mamuju', 'Majene', 'Polewali', 'Mamasa'],
  'Sulawesi Selatan': ['Makassar', 'Parepare', 'Palopo', 'Bone', 'Bulukumba'],
  'Sulawesi Tenggara': ['Kendari', 'Baubau', 'Kolaka', 'Raha'],
  'Maluku': ['Ambon', 'Tual', 'Masohi', 'Namlea'],
  'Maluku Utara': ['Ternate', 'Tidore', 'Tobelo', 'Jailolo'],
  'Papua': ['Jayapura', 'Sentani', 'Abepura', 'Serui'],
  'Papua Barat': ['Manokwari', 'Sorong', 'Fakfak', 'Kaimana'],
  'Papua Tengah': ['Nabire', 'Timika', 'Enarotali'],
  'Papua Pegunungan': ['Wamena', 'Mulia', 'Oksibil'],
  'Papua Selatan': ['Merauke', 'Tanah Merah', 'Bade'],
};

export const FAMILY_RELATIONS = [
  'Suami',
  'Istri',
  'Anak',
  'Ayah',
  'Ibu',
  'Kakek',
  'Nenek',
  'Kakak',
  'Adik',
  'Mertua',
  'Menantu',
  'Cucu',
  'Keponakan',
  'Lainnya',
];

export const HEALTH_CONDITIONS = [
  'Diabetes',
  'Hipertensi',
  'Kolesterol Tinggi',
  'Asam Urat',
  'Alergi Kacang',
  'Alergi Seafood',
  'Alergi Telur',
  'Alergi Susu',
  'Alergi Gluten',
  'Vegetarian',
  'Vegan',
  'Hamil',
  'Menyusui',
  'Diet Rendah Garam',
  'Diet Rendah Gula',
  'MPASI (6-12 bulan)',
  'Lainnya',
];

export const REGIONAL_CUISINES: Record<string, string[]> = {
  'Aceh': ['Mie Aceh', 'Kari Kambing', 'Ayam Tangkap', 'Kuah Pliek U'],
  'Sumatera Utara': ['Babi Panggang Karo', 'Arsik', 'Saksang', 'Bika Ambon'],
  'Sumatera Barat': ['Rendang', 'Gulai', 'Sate Padang', 'Dendeng Balado', 'Ayam Pop'],
  'Riau': ['Gulai Belacan', 'Asam Pedas', 'Lempuk Durian'],
  'Jambi': ['Gulai Ikan Patin', 'Tempoyak', 'Kue Padamaran'],
  'Sumatera Selatan': ['Pempek', 'Tekwan', 'Model', 'Mie Celor'],
  'Lampung': ['Seruit', 'Gulai Taboh', 'Kemplang'],
  'DKI Jakarta': ['Kerak Telor', 'Soto Betawi', 'Asinan Betawi', 'Gado-gado'],
  'Jawa Barat': ['Karedok', 'Lotek', 'Nasi Timbel', 'Soto Bandung', 'Batagor'],
  'Jawa Tengah': ['Gudeg', 'Lumpia Semarang', 'Soto Kudus', 'Nasi Liwet Solo'],
  'DI Yogyakarta': ['Gudeg', 'Bakpia', 'Ayam Goreng Kalasan', 'Sate Klathak'],
  'Jawa Timur': ['Rawon', 'Rujak Cingur', 'Soto Lamongan', 'Lontong Balap'],
  'Bali': ['Babi Guling', 'Ayam Betutu', 'Lawar', 'Sate Lilit'],
  'Nusa Tenggara Barat': ['Ayam Taliwang', 'Plecing Kangkung', 'Sate Rembiga'],
  'Nusa Tenggara Timur': ['Se\'i Sapi', 'Jagung Bose', 'Catemak Jagung'],
  'Kalimantan': ['Soto Banjar', 'Ayam Masak Habang', 'Mandai'],
  'Sulawesi Selatan': ['Coto Makassar', 'Pallubasa', 'Konro', 'Sop Saudara'],
  'Sulawesi Utara': ['Tinutuan', 'Cakalang Fufu', 'Rica-rica', 'Woku'],
  'Maluku': ['Papeda', 'Ikan Kuah Kuning', 'Kohu-kohu'],
  'Papua': ['Papeda', 'Ikan Bakar Manokwari', 'Sagu'],
};
